
export const storeProducts = [
    {
        id:1,
        title: "HP-notebook",
        img: "img/1.jpg",
        price: 45000,
        manufacturer: "HP",
        description: " DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart:false,
    count:0,
    total:0,
    
    },
{
    id: 2,
    title: "Dell inspiron",
    img: "img/2.jpg",
    price: 45800,
    manufacturer: "Dell",
    description: "DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart: false,
    count:0,
    total:0,
},
{
    id:3,
    title: "Lenovo Yoga 500",
    img: "img/3.jpg",
    price: 69000,
    manufacturer: "Lenovo",
    description: "DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart: false,
    count: 0,
    total: 0,
},{
    id:4,
    title: "Lenovo ideapad 100",
    img: "img/4.png",
    price: 56000,
    manufacturer: "Lenovo",
    description: "DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart: false,
    count: 0,
    total: 0,
},{
    id:5,
    title:"HP -ENVY X2",
    img: "img/5.png",
    price: 95000,
    manufacturer:"HP",
    description: "DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart: false,
    count: 0,
    total: 0,
},{
    id:6,
    title:"HP probook 450",
    img: "img/6.jpg",
    price:1100000,
    manufacturer:"HP",
    description: "DUMMY DESCRIPTION Even though React embraces functional programming, for instance with immutable data structures,classes are used to declare components. They are called ES6 class components. React mixes the goodparts of both programming paradigms.",
    incart: false,
    count: 0,
    total: 0,
},{
    id:7,
    title: "LG -md",
    img: "img/7.JPG",
    price: 16000,
    manufacturer:"LG",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:8,
    title:"LG GS",
    img: "img/8.jpg",
    price:19000, 
    manufacturer:"LG",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:9,
    title: "wiko-goa",
    img: "img/9.jpg",
    price:21000, 
    manufacturer:"WIKO" ,
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:10,
    title: "Wiko rainbow",
    img: "img/10.jpg",
    price:31555,
    manufacturer:"wiko" ,
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:11,
    title: "Windows Phone",
    img: "img/11.jpg",
    price:92000,
    manufacturer:"MICROSOFT",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:12,
    title: "Infinix Hot 4 -pro",
    img: "img/12.jpg",
    price:22500, 
    manufacturer:"infinix",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:13,
    title: "Infinix Hot 3 leak",
    img: "img/13.jpg",
    price:44000,
    manufacturer:"infinix",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:14,
    title: "Infinix-HOT 3 pro",
    img: "img/14.jpg",
    price:32499,
    manufacturer:"infinix", 
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:15,
    title: "Samsung-Galaxy S9+64GB ",
    img: "img/15.jpg",
    price: 73999,
    manufacturer:"samsung",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
},{
    id:16,
    title: "Google-Pixel 3 64gb",
    img: "img/16.jpg",
    price:100000, 
    manufacturer:"Google",
    description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
    incart: false,
    count: 0,
    total: 0,
}
]
export const detailProduct = {

        id:4,
        title: "Lenovo Yoga 500",
        img: "img/3.jpg",
        price: 69000,
        manufacturer: "Lenovo",
        description: "specifications Ram 4Gb storage 12Gb camera front 8mp back 12mp os android 7 battery 4000mAh",
        incart: false,
        count: 0,
        total: 0,
    
};